package ProfessorHomePage;

import entities.Video;
import Utils.Utils;

import javax.swing.*;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class VideoListElementView {
    //The main Panel of the VideoListElement
    private JPanel mainPanel;
    //The title of the video
    private JLabel videoTitle;
    //The preview image of the video
    private JLabel videoPreview;
    //The description of the video
    private JTextArea videoDescription;
    //The code of the video autogenerated by the database
    private JTextPane videoCode;
    //The button to go to the statistics page of the video
    private JButton seeStatisticsButton;
    //The button to modify the video description, the video title, the preview and the video file itself
    private JButton modifyButton;
    //The button to delete the video
    private JButton deleteButton;
    //The controller of this view
    private VideoListElement controller;

    /**
     * Creates a new view for a VideoListElement
     */
    public VideoListElementView() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        mainPanel.setBackground(Color.WHITE);
        setupTitle();
        previewDescriptionButtonsPanel();

    }

    /**
     * Sets up the label of the Video Title without text
     */
    private void setupTitle(){
        videoTitle = new JLabel();
        videoTitle.setFont(new Font(Font.SANS_SERIF,  Font.BOLD, Utils.SUBTITLE_WIDTH));
        videoTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        mainPanel.add(videoTitle);
        mainPanel.add(Box.createRigidArea(Utils.VERTICAL_RIGID_AREA_DIM15));

    }

    /**
     * Create a panel, the previewDescriptionButtonsPanel, that contains video preview, video description and all buttons
     */
    private void previewDescriptionButtonsPanel(){
        JPanel previewDescriptionButtonsPanel = new JPanel();
        previewDescriptionButtonsPanel.setLayout(new BoxLayout(previewDescriptionButtonsPanel, BoxLayout.X_AXIS));
        previewDescriptionButtonsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        mainPanel.add(previewDescriptionButtonsPanel);

        setupLeftPanel(previewDescriptionButtonsPanel);

        setupRightPanel(previewDescriptionButtonsPanel);

    }

    /**
     * Sets up the left panel of the given previewDescriptionButtonsPanel. It contains video preview and video description.
     * @param previewDescriptionButtonsPanel the panel to which the leftPanel will be added
     */
    private void setupLeftPanel(JPanel previewDescriptionButtonsPanel) {
        JPanel leftPanel = new JPanel();
        leftPanel.setLayout(new BoxLayout(leftPanel, BoxLayout.X_AXIS));
        leftPanel.setAlignmentY(Component.TOP_ALIGNMENT);
        leftPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        leftPanel.setBackground(Color.WHITE);
        previewDescriptionButtonsPanel.add(leftPanel);

        videoPreview = new JLabel();
        videoPreview.setAlignmentY(Component.TOP_ALIGNMENT);
        videoPreview.setAlignmentX(Component.LEFT_ALIGNMENT);
        leftPanel.add(videoPreview);
        leftPanel.add(Box.createRigidArea(new Dimension(Utils.HORIZONTAL_RIGID_AREA_DIM30)));

        videoDescription = new JTextArea();
        videoDescription.setEditable(false);
        videoDescription.setWrapStyleWord(true);
        videoDescription.setLineWrap(true);
        videoDescription.setPreferredSize(new Dimension(Utils.DESCRIPTION_WIDTH,Utils.DESCRIPTION_HEIGHT));
        videoDescription.setAlignmentY(Component.TOP_ALIGNMENT);
        leftPanel.add(videoDescription);
    }

    /**
     * Sets up the right panel of the given previewDescriptionButtonsPanel. It contains all the buttons and the video code.
     * @param previewDescriptionButtonsPanel the panel to which the rightPanel will be added
     */
    public void setupRightPanel(JPanel previewDescriptionButtonsPanel){
        JPanel rightPanel = new JPanel();
        rightPanel.setLayout(new BoxLayout(rightPanel, BoxLayout.PAGE_AXIS));
        rightPanel.setBackground(Color.white);
        rightPanel.setAlignmentY(Component.TOP_ALIGNMENT);
        previewDescriptionButtonsPanel.add(rightPanel);

        Utils utils = new Utils();

        seeStatisticsButton = new JButton("See statistics");
        seeStatisticsButton = utils.styleButtonOne(seeStatisticsButton);
        seeStatisticsButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        rightPanel.add(seeStatisticsButton);
        rightPanel.add(Box.createRigidArea(Utils.VERTICAL_RIGID_AREA_DIM15));

        modifyButton = new JButton("Modify");
        modifyButton = utils.styleButtonOne(modifyButton);
        modifyButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        rightPanel.add(modifyButton);
        rightPanel.add(Box.createRigidArea(Utils.VERTICAL_RIGID_AREA_DIM15));

        deleteButton = new JButton("Delete");
        deleteButton = utils.styleButtonTwo(deleteButton);
        deleteButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        rightPanel.add(deleteButton);
        rightPanel.add(Box.createRigidArea(Utils.VERTICAL_RIGID_AREA_DIM15));


        videoCode = new JTextPane();
        videoCode.setAlignmentX(Component.CENTER_ALIGNMENT);
        StyledDocument doc = videoCode.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        rightPanel.add(videoCode);
        rightPanel.add(Box.createRigidArea(Utils.VERTICAL_RIGID_AREA_DIM15));
    }

    /**
     * Modify all the empty labels and preview with the actual data from the video entity. Sets up the listener of the deleteButton
     * @param controller to access the model
     */
    public void installUI(VideoListElement controller) {
        this.controller = controller;
        setVideoInformation();

        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.deleteVideo();
            }
        });

        modifyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.dispatchModifyVideoEvent();
            }
        });

        seeStatisticsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.dispatchGoToStatisticsEvent();
            }
        });
    }

    /**
     * Sets all the labels and preview taking the actual data from the video entity
     */
    private void setVideoInformation(){
        Video video = controller.getVideo();
        videoTitle.setText(video.getTitle());
        videoDescription.setText(video.getDescription());
        videoCode.setText("Code:" + String.valueOf(video.getCode()));
        videoPreview.setIcon(new ImageIcon(new ImageIcon(video.getPreviewImage().getPath()).getImage().getScaledInstance(200, 113, Image.SCALE_SMOOTH)));
    }


    public JPanel getMainPanel() {
        return mainPanel;
    }

}
